### ISSUE TITLE
Test hangs on perl: res_query.c:262: __libc_res_nquery: Assertion `(hp != ((void *)0)) && (hp2 != ((void *)0))' failed

### ISSUE THREAD

**Issue by jasonblewis** [libwww-perl/WWW-Mechanize#40]
If you try and build this on Debian Jessie, the test will produce an error:

```
perl: res_query.c:262: __libc_res_nquery: Assertion `(hp != ((void *)0)) && (hp2 != ((void *)0))' failed.
```
and will hang on the t/local/failure.t test.

backtraces here:
http://sprunge.us/OgfY

and 
http://sprunge.us/XSgM

Thanks to TonyC for pointing me to a fix:
https://bbs.archlinux.org/viewtopic.php?pid=1607876#p1607876

On debian, temporarily disabling IPv6 solved my issue. with:

```
sudo sh -c 'echo 1 > /proc/sys/net/ipv6/conf/all/disable_ipv6'
```

**Comment by petdance** [comment]
Backtraces:

```
:~/.cpanm/work/1467269679.6722/WWW-Mechanize-1.75$ gdb --args perl -Mblib t/local/failure.t
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from perl...(no debugging symbols found)...done.
(gdb) r
Starting program: /home/reports/perl5/perlbrew/perls/perl-5.24.0/bin/perl -Mblib t/local/failure.t
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
1..15
ok 1 - require WWW::Mechanize;
ok 2 - An object of class 'LocalServer' isa 'LocalServer'
ok 3 - 'Created object' isa 'WWW::Mechanize'
ok 4 - An object of class 'HTTP::Response' isa 'HTTP::Response'
ok 5 - Success
ok 6 - Get webpage
ok 7 - It's HTML
ok 8 - Correct title
ok 9 - 10 links, please
ok 10 - Two form
perl: res_query.c:262: __libc_res_nquery: Assertion `(hp != ((void *)0)) && (hp2 != ((void *)0))' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff6cf2067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff6cf2067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff6cf3448 in __GI_abort () at abort.c:89
#2  0x00007ffff6ceb266 in __assert_fail_base (fmt=0x7ffff6e24238 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x7ffff5a75368 "(hp != ((void *)0)) && (hp2 != ((void *)0))", file=file@entry=0x7ffff5a75307 "res_query.c", line=line@entry=262, 
    function=function@entry=0x7ffff5a753b0 <__PRETTY_FUNCTION__.11991> "__libc_res_nquery") at assert.c:92
#3  0x00007ffff6ceb312 in __GI___assert_fail (assertion=assertion@entry=0x7ffff5a75368 "(hp != ((void *)0)) && (hp2 != ((void *)0))", file=file@entry=0x7ffff5a75307 "res_query.c", 
    line=line@entry=262, function=function@entry=0x7ffff5a753b0 <__PRETTY_FUNCTION__.11991> "__libc_res_nquery") at assert.c:101
#4  0x00007ffff5a6d0bf in __GI___libc_res_nquery (statp=statp@entry=0x7ffff7066be0 <_res>, name=0x7fffffffc510 "blahblahblah.xx-only-testing.foo.localnet", class=class@entry=1, 
    type=type@entry=62321, answer=answer@entry=0x7fffffffce70 "\356i\201\200", anslen=anslen@entry=2048, answerp=answerp@entry=0x7fffffffd6b0, answerp2=answerp2@entry=0x7fffffffd6c0, 
    nanswerp2=nanswerp2@entry=0x7fffffffd6a0, resplen2=resplen2@entry=0x7fffffffd6a4, answerp2_malloced=answerp2_malloced@entry=0x7fffffffd6a8) at res_query.c:262
#5  0x00007ffff5a6d210 in __libc_res_nquerydomain (statp=statp@entry=0x7ffff7066be0 <_res>, name=name@entry=0x192c3d0 "blahblahblah.xx-only-testing.foo", domain=<optimized out>, 
    class=class@entry=1, type=type@entry=62321, answer=answer@entry=0x7fffffffce70 "\356i\201\200", anslen=anslen@entry=2048, answerp=answerp@entry=0x7fffffffd6b0, 
    answerp2=answerp2@entry=0x7fffffffd6c0, nanswerp2=nanswerp2@entry=0x7fffffffd6a0, resplen2=resplen2@entry=0x7fffffffd6a4, answerp2_malloced=answerp2_malloced@entry=0x7fffffffd6a8)
    at res_query.c:594
#6  0x00007ffff5a6d6ad in __GI___libc_res_nsearch (statp=0x7ffff7066be0 <_res>, name=name@entry=0x192c3d0 "blahblahblah.xx-only-testing.foo", class=class@entry=1, 
    type=type@entry=62321, answer=answer@entry=0x7fffffffce70 "\356i\201\200", anslen=anslen@entry=2048, answerp=answerp@entry=0x7fffffffd6b0, answerp2=answerp2@entry=0x7fffffffd6c0, 
    nanswerp2=nanswerp2@entry=0x7fffffffd6a0, resplen2=resplen2@entry=0x7fffffffd6a4, answerp2_malloced=answerp2_malloced@entry=0x7fffffffd6a8) at res_query.c:423
#7  0x00007ffff5c7eacb in _nss_dns_gethostbyname4_r (name=name@entry=0x192c3d0 "blahblahblah.xx-only-testing.foo", pat=pat@entry=0x7fffffffdcb0, 
    buffer=buffer@entry=0x7fffffffd740 "+\244\222\001", buflen=buflen@entry=1064, errnop=errnop@entry=0x7fffffffdca0, herrnop=herrnop@entry=0x7fffffffdcc0, ttlp=ttlp@entry=0x0)
    at nss_dns/dns-host.c:315
#8  0x00007ffff6d90951 in gaih_inet (name=<optimized out>, name@entry=0x192c3d0 "blahblahblah.xx-only-testing.foo", service=<optimized out>, req=req@entry=0x7fffffffdef0, 
    pai=pai@entry=0x7fffffffdd98, naddrs=naddrs@entry=0x7fffffffdd94) at ../sysdeps/posix/getaddrinfo.c:862
#9  0x00007ffff6d92afd in __GI_getaddrinfo (name=0x192c3d0 "blahblahblah.xx-only-testing.foo", service=0x16ce390 "80", hints=0x7fffffffdef0, pai=0x7fffffffdee8)
    at ../sysdeps/posix/getaddrinfo.c:2418
#10 0x00007ffff522fb4b in xs_getaddrinfo () from /home/reports/perl5/perlbrew/perls/perl-5.24.0/lib/5.24.0/x86_64-linux/auto/Socket/Socket.so
#11 0x00000000004b6098 in Perl_pp_entersub ()
#12 0x00000000004aea73 in Perl_runops_standard ()
#13 0x00000000004425d6 in perl_run ()
#14 0x00000000004201e5 in main ()
(gdb) 

0
```

and

```
reports@debian:~/.cpanm/work/1467337034.30451/WWW-Mechanize-1.75$ gdb --args perl -T t/autocheck.t
GNU gdb (Debian 7.7.1+dfsg-5) 7.7.1
Copyright (C) 2014 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from perl...(no debugging symbols found)...done.
(gdb) r
Starting program: /home/reports/perl5/perlbrew/perls/perl-5.24.0/bin/perl -T t/autocheck.t
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
1..5
ok 1 - require WWW::Mechanize;
ok 2 - An object of class 'WWW::Mechanize' isa 'WWW::Mechanize'
perl: res_query.c:262: __libc_res_nquery: Assertion `(hp != ((void *)0)) && (hp2 != ((void *)0))' failed.

Program received signal SIGABRT, Aborted.
0x00007ffff6cf2067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56	../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) bt
#0  0x00007ffff6cf2067 in __GI_raise (sig=sig@entry=6) at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff6cf3448 in __GI_abort () at abort.c:89
#2  0x00007ffff6ceb266 in __assert_fail_base (fmt=0x7ffff6e24238 "%s%s%s:%u: %s%sAssertion `%s' failed.\n%n", 
    assertion=assertion@entry=0x7ffff68b0368 "(hp != ((void *)0)) && (hp2 != ((void *)0))", file=file@entry=0x7ffff68b0307 "res_query.c", line=line@entry=262, 
    function=function@entry=0x7ffff68b03b0 <__PRETTY_FUNCTION__.11991> "__libc_res_nquery") at assert.c:92
#3  0x00007ffff6ceb312 in __GI___assert_fail (assertion=assertion@entry=0x7ffff68b0368 "(hp != ((void *)0)) && (hp2 != ((void *)0))", 
    file=file@entry=0x7ffff68b0307 "res_query.c", line=line@entry=262, function=function@entry=0x7ffff68b03b0 <__PRETTY_FUNCTION__.11991> "__libc_res_nquery") at assert.c:101
#4  0x00007ffff68a80bf in __GI___libc_res_nquery (statp=statp@entry=0x7ffff7066be0 <_res>, name=0x7fffffffc510 "blahblablah.xx-nonexistent.foo.localnet", class=class@entry=1, 
    type=type@entry=62321, answer=answer@entry=0x7fffffffce70 "\037o\201\200", anslen=anslen@entry=2048, answerp=answerp@entry=0x7fffffffd6b0, 
    answerp2=answerp2@entry=0x7fffffffd6c0, nanswerp2=nanswerp2@entry=0x7fffffffd6a0, resplen2=resplen2@entry=0x7fffffffd6a4, 
    answerp2_malloced=answerp2_malloced@entry=0x7fffffffd6a8) at res_query.c:262
#5  0x00007ffff68a8210 in __libc_res_nquerydomain (statp=statp@entry=0x7ffff7066be0 <_res>, name=name@entry=0x14d3ed0 "blahblablah.xx-nonexistent.foo", domain=<optimized out>, 
    class=class@entry=1, type=type@entry=62321, answer=answer@entry=0x7fffffffce70 "\037o\201\200", anslen=anslen@entry=2048, answerp=answerp@entry=0x7fffffffd6b0, 
    answerp2=answerp2@entry=0x7fffffffd6c0, nanswerp2=nanswerp2@entry=0x7fffffffd6a0, resplen2=resplen2@entry=0x7fffffffd6a4, 
    answerp2_malloced=answerp2_malloced@entry=0x7fffffffd6a8) at res_query.c:594
#6  0x00007ffff68a86ad in __GI___libc_res_nsearch (statp=0x7ffff7066be0 <_res>, name=name@entry=0x14d3ed0 "blahblablah.xx-nonexistent.foo", class=class@entry=1, 
    type=type@entry=62321, answer=answer@entry=0x7fffffffce70 "\037o\201\200", anslen=anslen@entry=2048, answerp=answerp@entry=0x7fffffffd6b0, 
    answerp2=answerp2@entry=0x7fffffffd6c0, nanswerp2=nanswerp2@entry=0x7fffffffd6a0, resplen2=resplen2@entry=0x7fffffffd6a4, 
    answerp2_malloced=answerp2_malloced@entry=0x7fffffffd6a8) at res_query.c:423
#7  0x00007ffff6ab9acb in _nss_dns_gethostbyname4_r (name=name@entry=0x14d3ed0 "blahblablah.xx-nonexistent.foo", pat=pat@entry=0x7fffffffdcb0, 
    buffer=buffer@entry=0x7fffffffd740 "\376UW", buflen=buflen@entry=1064, errnop=errnop@entry=0x7fffffffdca0, herrnop=herrnop@entry=0x7fffffffdcc0, ttlp=ttlp@entry=0x0)
    at nss_dns/dns-host.c:315
#8  0x00007ffff6d90951 in gaih_inet (name=<optimized out>, name@entry=0x14d3ed0 "blahblablah.xx-nonexistent.foo", service=<optimized out>, req=req@entry=0x7fffffffdef0, 
    pai=pai@entry=0x7fffffffdd98, naddrs=naddrs@entry=0x7fffffffdd94) at ../sysdeps/posix/getaddrinfo.c:862
#9  0x00007ffff6d92afd in __GI_getaddrinfo (name=0x14d3ed0 "blahblablah.xx-nonexistent.foo", service=0x1506020 "80", hints=0x7fffffffdef0, pai=0x7fffffffdee8)
    at ../sysdeps/posix/getaddrinfo.c:2418
#10 0x00007ffff5432b4b in xs_getaddrinfo () from /home/reports/perl5/perlbrew/perls/perl-5.24.0/lib/5.24.0/x86_64-linux/auto/Socket/Socket.so
#11 0x00000000004b6098 in Perl_pp_entersub ()
#12 0x00000000004aea73 in Perl_runops_standard ()
#13 0x00000000004425d6 in perl_run ()
#14 0x00000000004201e5 in main ()
(gdb) 

0
```
